# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dtube',
                'doc_host': 'https://LVG77.github.io',
                'git_url': 'https://github.com/LVG77/dtube',
                'lib_path': 'dtube'},
  'syms': {'dtube.core': {'dtube.core.foo': ('core.html#foo', 'dtube/core.py')}}}